# 服务器配置参数列表


###########################################################
#                     全局参数                             #
###########################################################
host: 0.0.0.0
port: 5500


log_dir: "./logs"                                                      # 日志保存路径
cert_file_path: "/home/zj/chatbot/ssh_files/server"                  # ssh证书文件路径


